# =============================================================================
# REDIS SESSION STORE - Dedicated Configuration
# =============================================================================
# Separate Redis setup for session management and caching
# Can be used standalone or combined with other services

version: '3.8'

services:
  # Redis Session Store - Optimized for session management
  redis:
    image: redis:7-alpine
    container_name: azure-b2c-redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - azure-b2c-network

  # Redis Commander - Web-based Redis management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: azure-b2c-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      - HTTP_USER=admin
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - azure-b2c-network

volumes:
  redis_data:
    driver: local

networks:
  azure-b2c-network:
    external: true 